### ISSUE TITLE
Needs a new release tag

### ISSUE THREAD

**Issue by davejtoews** [LasseRafn/php-hexer#7]
This PR was merged two years ago but no release has been tagged since: https://github.com/LasseRafn/php-hexer/commit/b8af38943e282637067d07ac8e1705b15cde21b6

**Comment by LasseRafn** [comment]
@davejtoews thanks for the reminder! So sorry, this has been done now!

https://github.com/LasseRafn/php-hexer/releases/tag/v1.10
